spring.application.name=Backend-Tasks
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/demo_restapi
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

jwt.secret=mysecretkeymysecretkeymysecretkeyjwtauthenticationforspringsecurity
jwt.expiration=1800000
jwt.refresh.expiration=604800000 